language: node_js
node_js:
- node
- '8'
- '7'
- '6'
- '5'
- '4'
sudo: false
before_install:
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.3.2
- export PATH=$HOME/.yarn/bin:$PATH
- yarn global add greenkeeper-lockfile@1
cache: false
install: yarn install --ignore-scripts
before_script: greenkeeper-lockfile-update
script: yarn
after_script: greenkeeper-lockfile-upload
before_deploy: yarn tidy-ci
deploy:
  provider: npm
  email: github-external-bot@holvonix.com
  skip_cleanup: true
  api_key:
    secure: cgMVxqpZmFnvKfdxQgvs1l1hynavaZl0leh4jTCgtXegS/OhcAlFeBcpOplWHdoJWM2Kunpx9MvnEs/93JQAv6VwlyB7WBEOUg3fPTVw3GsXoRzuKcXVo07lzctjhqOwroKT0IwFSa5QmD6i0nu6Q+iCnKMLMSu1arpxXyHvVeCHQgO4nGohXWYZsCly7c1bYNGvNu4UksoGwl/aUo+XySP6CrTlyt4j0rmNXBvzUv6536XhNKzuu4W4tes+MUGC21DnwJCs0TlB2nwT8GK45hHuBmLWQ9pJ/sbDP0UsDdBXD2mLTP170s7KOCsJOFK6zJKsjfTww9r1AI1s33MPi7Xu9V28ynP8gRwgiGkimuK5zoAyJoEMUQfsaI+qIE4oVSwXLLoHP0Z4C82v0zol4/n+gvu6TWt+ao2HeCDhGv49yIr+4/OqvRNGdijH60bW4E6o15CJYHP1tmvz/q5vFLg24Ft2nsPnKWG+JspkAjsDJxYUNHnP9Dn4DsRx01nyC8F0Ud2PyiMl12xDLnKYmi/qFRx3u63mx0Vmp89lgZIHH75a596TDWJN4PmNZdiCGQ/K+UDbMBNgqcFiRKfJgUmj684BMVMdpN8+IykGrgqV392dU8/vyjpwTLgH536dM6eDkB4sRKKsU5H/sM/tPDczRuTAAs0g2kYZJDbdr4o=
  on:
    node: node
    tags: true
    branch: master
    repo: holvonix-open/json2array
env:
  global:
  - secure: o65Km+xly84qErkw+PVgfYBQ7wSreOqSnI/7jfO37AEK+vj5AX9TldZS7LtGiDw2QcmsY8o/hQ6j5QJACZjNRrplCs+3hz32upxyfmO4uMKCd3IIP97OsdORaQwnsgZvtyRncPfYNmvxjIgLMEjKjHD1riwTs7nY6pbBEl4WJ3GpO2fDkPVtPexlCs97tg9VZsTlr6zk0us+ztZJNwOxtNlfzErOvRpS7a/jxuJszoaGAcPRMxopEyu9UrDnFHU2/uxtcoTqWXn+y+cAaHGqR9udbQvex4eJuzYBYBneponZDi0ZA8h3nhp+4TNJ6qKUV80hkjYU1S99hrnnvXB7BAape7escVaPo5mx4TTtREwgC9jMNxv/9lBNvCZY5qEYw8sg7fOWPSNzD3geEURstqkhKo7+NqJ69hdIymmI2mWS4xH1OTe5CbzfJ6nlS5FxcWftqxSgkIM0wQJ4vRIlmoW5tFlOWWAcjPFZ6RLOyWpNcn5Gvtvh8Z5vPHu3/fcp6qvZ/LLr2Yrr/Hzda15smdYXpTrzVdttRnase9RUlXzN1i+ptYO4XS8HjyMItARW5YLAFZ5Ia/DhQvvZ6e4idTsN+oWy5BJ36YmBSevwVV7YKdy/W5bGnMqtWM4tkTjfU7dlwduCK+EpHEHDO+wHhq5EU9vFPaP9bXjKt/5dQfc=
  - secure: XwHlAz1/y+KZIevs3rQ1YLTiiMleBmC/VwCVGrsoB58wuzFPbzdzWr6NekBaBYyBqsdUlT+wh7bEwByH1rBAZNO83+UI+d646trhdM5WEKCvMXQlt6z7in2xjNh+eYqKVJ5XMsI6pLXNQH9kiIALI8arEkYArmM/xupydCchI0JoIKU8XJwmUXSS95NyI3sT91IOZVdBYEai8ZkiriSNH/Jx2W7GW7CUOdwiUSxHGlefp7NkxW6VasmUGO46/YVIvvqGGTONNabG2+UTPOED4iKXlhw9efqa75Bb8lAyR6rLaihpLJcuusFLQYQThT8GiEYIFqHFzOGOOyZOiqkPOqgrrY0vs3FIHjQyChDHS9jYEYuHJklxMubfo55j+l7sJ2uXMUfHmPQjPPtJ88OKsuGLzmk95BzryVe+NXmCVcLlBUnrHALO8+W5J/X4yfHjcQbSs1pC3KfkoL6JUvI/MnBioGEZUmjTf00tdaTgumILUc+Gsnqz8+SEejyaPwCEvU7UhgbqoaGzBQCII2xaeHXaxRHSn8k0NoeZ10kiDsi6qAQ90CGOprD1C3Ft9koq3PgzkAsOhICIf3b6mOsXAcGyUbFeoCBYKeJRqjCNLc0HrO1H4PBG4OCvEliEYJbWMid+mNQYqQI5otdk6gMrrHJMphV30uNRfvdChyJTDf8=
